#+TITLE: AutOrg - autonomous distributed information system
#+DATE: <2010-06-13 Sun>

DOCS { [[file:autonomy-is-organization.org][About]] | [[file:API.org][API]] | Book | [[file:org-gtd.org][GTD]] | [[file:glossary.org][Glossary]] | [[file:index.org][Index]] }

* The AutOrg Project

AutOrg stands for [[file:autonomy-is-organization.org][Autonomy is Organization]].

AutOrg is  made of words  and code.   It comes in  the form of  a book
describing the  implementation of  [[file:org-gtd.org][GTD]] methodology with  existing Unix
utilities, and a software package  that implements it.  AutOrg is made
with AutOrg (well, at least at some point it will. :)

The synergy between powerful developer  tools and GTD, when applied to
groups,  /evolves   into  an   ADIS/  :  an   Autonomous,  Distributed
Information System for developers, authors, publishers and curators to
organize a decentralized publishing system out of simple commands.

AutOrg's secret plot is to reverse the current vision of the Social
Web, by putting your social network back where it belongs: localhost.

** Hacking AutOrg

  `git clone git://code.dyne.org/autorg.git`

  The Git repository is also viewable on the Web:

  http://code.dyne.org/?r=autorg

  Read the [[file:hacking.org][AutOrg Developer Guide]].

* The AutOrg Book

We want to publish a book on implementing GTD methodology by
integrating available Unix utilities.  
* The AutOrg Command

The `autorg` command  provides a command line interface  to the AutOrg
API.   `autorg`  can be  used  on the  command  line,  or in  scripts.
AutOrg's Uzbl configuration uses that command to provide a GUI.

The `autorg` command is documented in the [[file:API.org][Application Programming
Interface]] file.

** AutOrg Integration

AutOrg follows the Unix Philosophy: 
#+begin_quote
    Write programs that do one thing and do it well. Write programs to
    work together. Write programs to handle text streams, because that
    is a universal interface.
#+end_quote

*** Editing

AutOrg uses Emacs extensively.  But it doesn't require you to use it.

*Any plain text editor* can be used, although we recommend using one
that supports Orgmode syntax-highlighting and features.

We're planning to support a web-based editor someday.

*** Sharing

You won't go anywhere with AutOrg without *Git*.

The good news is that the `autorg` command wraps Git calls for you and
should be transparent for normal use.

That's all, folks!  Announces are taken care of using different
configurable strategies (PSYC, HTTP, Mailto, XMPP.)  By default, an
AutOrg project is announced via PSYC to the *AutOrg Global Project
Release Announcement channel*

  [[https://hinezumi.im:8443?randomnick=1&channels=@AutOrg&prompt=0][psyc://hinezumi.im/@AutOrg#announce-releases-projects]] 
  (click to join the @AutOrg room in your web browser)

*** Printing

AutOrg provides ready-to-print documents via the `make`.

They come in PDF format, for reading on a device, or printing on
paper.  Export options can be customized to achieve a specific style.

*** Web Browsing

You can use  *any Web browser* to read  AutOrg files: they're exported
in plain HTML.  Some features can be added with Javascript.

To interact with Emacs using  Org-protocol (e.g.: edit the .org source
file  by clicking  a link  on the  generated HTML  page), you  need to
modify your browser configuration to add a protocol handler.

You can also  use Uzbl with the provided configuration  to have it all
setup.

*** Optimal Setup

If  you install  and configure  the  following tools,  you'll get  the
ultimate  GTD,  Authoring and  Publishing  environment  to use  AutOrg
optimally.   The  contrib/  directory   in  the  source  code  provide
alternate options for different tastes.

**** Emacs

 - Emacs 23.2+ (for Socket compatibility with Uzbl)
 - WxWidget patch for embedding Uzbl inside Emacs

**** Orgmode

 - git Orgmode

**** Uzbl

  - to use as the AutOrg web browser
  - AutOrg configuration for Uzbl include:
    - Org-protocol support (open .org source in Emacs from the HTML)
    - Key bindings to autorg commands
    - Collections discovery and management
    - Release Management

**** Zsh

  - Provide key bindings for AutOrg
  - Provide shortcuts to Uzbl

