#!/bin/sh
#
# mkscript - Generate a script from configuration
#
# FIXME: license

script="$1"  # The script's filename
autorg="$2"  # Path to autorg installation
domain="$3"  # Configured domain name
orgmode="$4" # Path to org-mode/lisp files

if [ ! -f $script.in ]; then
    echo " EE Missing target $script.in: mkscript aborted."
    exit 1
fi

sed \
    -e "s@%autorg_path%@$autorg@g" \
    -e "s@%domain%@$domain@g" \
    -e "s@%orgmode_path%@$orgmode@g" \
    $script.in > $script

echo " II Generated $script"
